
ALTER TABLE USERS 
ADD VILLAGE VARCHAR(50);


UPDATE USERS
SET VILLAGE = 'East Edavalli'
WHERE ID = 1 OR ID = 5 OR ID = 6 OR ID = 7 OR ID = 8;

UPDATE USERS
SET VILLAGE = 'Eluru'
WHERE ID = 2 OR ID = 3;

UPDATE USERS
SET VILLAGE = 'Tuni'
WHERE ID = 4;

UPDATE USERS 
SET AGE = AGE+1
WHERE AGE = 20;

UPDATE USERS
SET AGE = 100
WHERE NAME ILIKE 'VIJAY%';

UPDATE USERS
SET NAME = 'Varun (Kodi Guddu)'
WHERE ID = 8 AND NAME = 'VARUN (Kodi Guddu)';

SELECT * FROM USERS;
