CREATE TABLE IF NOT EXISTS STUDENTS(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    AGE INTEGER,
    VILLAGE VARCHAR(150) ,
    EMAIL VARCHAR(150) NOT NULL,
    MOBILE BIGINT,
    ADDRESS JSONB
)   ;

INSERT INTO STUDENTS(NAME,AGE,VILLAGE,EMAIL,MOBILE,ADDRESS) VALUES
    ('Durga Prasad Kota',20,'East Yadavlli','durgaprasadkota@gmail.com',7286945898,'{"Street":"OC Colony","Mandal":"Kamavarapukota"}');


SELECT ADDRESS->>'Street' AS STREET
FROM STUDENTS;

ALTER TABLE  STUDENTS
DROP AGE;

ALTER TABLE STUDENTS 
ADD COLUMN AGE INTEGER CHECK (AGE >= 18) ;

ALTER TABLE  STUDENTS
DROP AGE;


UPDATE  STUDENTS
SET VILLAGE = 'Yadavalli' 
WHERE EMAIL ILIKE 'DURGAPRASADKOTA%' ;

UPDATE STUDENTS
SET VILLAGE = REPLACE(VILLAGE,'Yadavalli','East Yadavalli')
WHERE VILLAGE ILIKE 'YADAVALLI';

UPDATE STUDENTS
SET COMPANY_NAME = concat('Mr.',NAME);

SELECT * FROM STUDENTS;